### ISSUE TITLE
Leaderboard button and local storage 

### ISSUE THREAD

**Issue by Anton1sk0** [Kindergarten-2024/tournament-app-fe#3]
Problem:
The leaderboard button in our application is currently not functioning correctly (localhost:3000 instead of the real URL), preventing users from accessing the leaderboard. Also when users reload the leaderboard data miss

Expected Behavior:
The expected behavior is that users should be able to click on the leaderboard button to view the leaderboard and its contents, and also be able to reload without miss the data.

**Comment by apostolos-k** [comment]
Fixed
