### ISSUE TITLE
Timing Issue with First Question in Second Round

### ISSUE THREAD

**Issue by Anton1sk0** [Kindergarten-2024/tournament-app-fe#5]
Problem:
Currently, we are experiencing a bug within our application where the first question in the second round of a game seems to miss.

Expected Behavior:
The expected behavior is that all questions should be presented correctly

**Comment by apostolos-k** [comment]
TIP: It seems that when we clear local storage (or refresh the page) when we wait for the 2nd round to begin, the issue is fixed.

**Comment by Anton1sk0** [comment]
Also , seems like web socket does not receive the (first) question dto .

**Comment by apostolos-k** [comment]
Fixed
